[package]
name = "rvg"
version = "0.0.1"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
edition = "2018"

license = "MIT / BSL-1.0"
description = "Vector graphics format."
documentation = "https://docs.rs/rvg"
homepage = "https://aldarobot.plopgrizzly.com/rvg/"
repository = "https://github.com/Aldarobot/rvg"
readme = "README.md"

[dependencies]
miniz_oxide = "0.2"

[dev-dependencies]
png = "0.10"
usvg = "0.6"
footile = "0.3" #{ path = "../footile" } # "0.3"
