[package]
name = "rvg"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeronaldaron@gmail.com>"]
edition = "2018"

[dependencies]
miniz_oxide = "0.2"

[dev-dependencies]
png = "0.10"
usvg = "0.6"
footile = { path = "../footile" } # "0.3"
