[package]
name = "rvg"
version = "0.0.1"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
edition = "2018"

[dependencies]
miniz_oxide = "0.2"

[dev-dependencies]
png = "0.10"
usvg = "0.6"
footile = "0.3" #{ path = "../footile" } # "0.3"
